spring:
  datasource:
    url: jdbc:postgresql://db:5432/barcamp
    username: barcamp
    password: barcamp
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
#
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    open-in-view: false
#
#  flyway:
#    enabled: true

server:
  port: 8080